### ISSUE TITLE
MoM resources?

### ISSUE THREAD

**Issue by twhughes** [MichaelRichardson12/mom_python#1]
Hey @MichaelRichardson12, this is a really nice package!  It's hard to find a simple implementation of MoM these days.  If you dont mind me asking, what resources did you use to help when writing this code?  Was it from a class project?  I've been looking for some notes on the subject to study and try to implement my own without much luck.

Thanks

**Comment by michaelprichardson** [comment]
Hi @twhughes, thanks so much. This was actually part of my master's thesis. I needed to compare results from other solvers against a 2D mom so I made my own. The two sources I used as references are A. F. Peterson, S. L. Ray, and R. Mittra. Computational methods for electromagnetics and J. M. Jin. Theory and Computation of Electromagnetic Fields.

**Comment by twhughes** [comment]
Cool, thanks for your response!  I'll check those books out.
